Work on GitHub actions.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,12 +1,15 @@
 name: Publish package to the Maven Central Repository
 on:
   release:
-    types: [created]
+    types: 
+      - created
 jobs:
   publish:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
+
       - name: Set up Maven Central Repository
         uses: actions/setup-java@v4
         with:
@@ -17,11 +20,20 @@ jobs:
           server-password: MAVEN_PASSWORD
           gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
           gpg-passphrase: MAVEN_GPG_PASSPHRASE
-      - name: Set version
-        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
-      - name: Publish package
-        run: mvn -P release --batch-mode deploy -DskipTests
-        env:
-          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
-          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
-          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
+
+      - name: Validate release tag format
+        run: |
+          TAG_NAME="${{ github.event.release.tag_name }}"
+          if [[ ! "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag name '$TAG_NAME' does not match the format X.Y.Z where X, Y, and Z are non-negative integers."
+            exit 1
+          fi
+          echo "Tag name '$TAG_NAME' is valid."
+
+
+    #   - name: Publish package
+    #     run: mvn -Prelease -Drevision=${{ github.event.release.tag_name }} --batch-mode deploy
+    #     env:
+    #       MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
+    #       MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
+    #       MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
